### ISSUE TITLE
Cryptographic DOOM!

### ISSUE THREAD

**Issue by sarciszewski** [tebru/aes-encryption#1]
http://www.thoughtcrime.org/blog/the-cryptographic-doom-principle/

http://www.daemonology.net/blog/2009-06-24-encrypt-then-mac.html

https://github.com/tebru/aes-encryption/blob/4d4c7d22db1cf23cfbeed4b43a34812b5544dd56/src/AesEncrypter.php#L62-L77

**Comment by natebrunette** [comment]
Hey, thanks for the links.  I'll read through them and then revisit the library implementation accordingly.
